//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub osu_id: i64,
    pub discord_id: i64,
    pub is_blacklisted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::skin::Entity")]
    Skin,
}

impl Related<super::skin::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Skin.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
